//
//  BackupEncryptionKey+Model.swift
//  Occulta
//
//  SwiftData model for the per-depth Backup Encryption Key (BEK).
//
//  The BEK is a random 32-byte key used to seal the `.occbak` export file.
//  It is Shamir-split and distributed to trustees so a new device can
//  reconstruct it from k shards and decrypt a backup file to restore the vault.
//
//  Replaces the previous 32-slot fixed-width array file (`VaultManager.Backup.LayerStore`,
//  deleted) — one row per depth now, stored like everything else this branch already moved
//  off blob/array storage (`Manager.LayerStore` for contacts, `VaultEntry.deletionToken` for
//  vault entries). See `VAULT_KEY_LAYERING.md` for the full design history.
//
//  Every row is always in exactly one of three states, indistinguishable from raw SQL
//  alone — the property the old array's "always 32 slots, real or filler" design provided,
//  reproduced here per-row instead of per-file-offset:
//
//  1. **Filler** (never claimed). `depth`, `deletionToken`, and `encryptedPayload` are all
//     `SecRandomCopyBytes`-generated bytes of the correct fixed length — never run through a
//     real seal, so they never decrypt. Random bytes of the right length are cryptographically
//     indistinguishable from genuine ciphertext+tag without the key, so this needs no key
//     material to generate and can happen eagerly at first launch, before Secure Mode is ever
//     configured — see `VaultManager`'s launch-time filler top-up.
//  2. **Live.** `depth` decodes to the real depth (`DepthCodec`, exact-match, not a ceiling —
//     same semantics as `VaultEntry.visibleThroughDepth`), `deletionToken` decodes to
//     `liveToken`, `encryptedPayload` decodes to a real `Payload`.
//  3. **Orphaned.** Same as live, but `deletionToken` decodes to `orphanedToken`. `depth`/
//     `encryptedPayload` are left as historical record, never wiped — exclusion from every
//     functional read is what makes the row inert, mirroring `VaultEntry.deletionToken`'s own
//     doc comment exactly.
//
//  Transitions are one-way: filler → live → orphaned, never backward. A claimed row never
//  reverts to filler and gets reclaimed by an unrelated depth later — recycling a *row* the
//  same way depth *numbers* already get recycled across unrelated duress sessions would just
//  reintroduce the bug this design exists to close (see `Manager.Security.orphanBackupKeys`).
//
//  Privacy model — encryption at rest:
//  - `id` (plaintext) — random per row, bound into AAD.
//  - `depth`, `deletionToken` — sealed under the **local DB key** (`Manager.Ambient`'s
//    hybrid key), not the vault key. Forced, not a style choice: orphaning has to run from
//    `Manager.Security.deactivateSecureMode`/`forceDeactivateForRecovery`, neither of which
//    ever derives the vault key. If these fields were vault-key-sealed, orphaning a freed
//    depth's row could not happen there at all.
//  - `encryptedPayload` — AES-GCM sealed under the vault key (biometric-gated), exactly as
//    before. Contains the raw 32-byte BEK, a stable distributionID for shard routing, and the
//    SSS shard distribution metadata for BEK shards.
//  - Cold-disk forensics learns nothing: row count is always at least 32 regardless of history
//    (filler), which of the 32-plus rows are live/orphaned/filler needs the local key, and
//    what a live row's payload actually contains needs the vault key on top of that.
//
//  Lifecycle:
//  - 32 filler rows created eagerly at first launch (see `VaultManager`'s launch sequence) —
//    a starting baseline, not a hard cap. Once every prefilled row is claimed (live or
//    orphaned), further first-time backup setups insert genuinely new rows beyond 32,
//    uncapped, no eviction — confirmed acceptable since a row is only ever created by an
//    explicit "set up backup at this depth" action, not everyday use.
//  - A filler row is claimed by `VaultManager.Backup.persist(_:vaultKey:currentDepth:modelContext:)`
//    on first backup setup for a depth.
//  - `encryptedPayload` updates in place on distribution (new shard metadata), status
//    transitions, reconstruction, and rotation — same row, same `id`, once claimed.
//  - Orphaned by `Manager.Security.orphanBackupKeys(freedFrom:)` when `deactivateSecureMode`/
//    `forceDeactivateForRecovery` frees a depth.
//

import Foundation
import CryptoKit
import SwiftData

@Model
final class BackupEncryptionKey {

    // MARK: Persisted fields

    /// Random per-row identifier. Bound into AAD; mutating invalidates decryption. Assigned
    /// at row-insertion time, including for filler rows — this is what keeps ciphertext from
    /// one row from authenticating under another's AAD, the same property slot-index binding
    /// gave the old array; `depth` is never bound into AAD, since it's not attacker-supplied
    /// input to the seal call and `id`-uniqueness already closes the swap this would defend.
    var id: UUID = UUID()

    /// Encrypted `Int` depth stamp — the depth this row was claimed for, exact-match (not a
    /// ceiling). `nil` never occurs for a stored row; a filler row's `depth` holds random
    /// bytes that fail to decrypt, which is what `isUnclaimed(usingKey:)` checks for. Sealed
    /// under the local DB key — see the file header for why.
    var depth: Data? = nil

    /// Whether this row has been orphaned. Always populated for a stored row — see the file
    /// header's three-state description. Sealed under the local DB key.
    var deletionToken: Data? = nil

    /// Sealed `Payload`: nonce(12B) ∥ ciphertext ∥ tag(16B) — CryptoKit `.combined`.
    /// AAD = `aad()`. Key = vault key (biometric-gated, same wrapping as per-entry PEKs).
    /// A filler row's `encryptedPayload` is the same fixed length, filled with random bytes
    /// that were never run through a real seal.
    var encryptedPayload: Data = Data()

    // MARK: Orphaning

    /// Fixed-width sentinel plaintexts for `deletionToken`. Both are one byte and encrypt to
    /// the same ciphertext length — nothing about the sealed bytes reveals which one is
    /// inside without the key. Mirrors `VaultEntry.liveToken`/`.orphanedToken` exactly.
    static let liveToken:     Data = Data([0])
    static let orphanedToken: Data = Data([1])

    /// Whether this row has been orphaned. Fail-safe: a `deletionToken` that is nil,
    /// undecryptable, or decrypts to neither known sentinel is treated as orphaned — the same
    /// "ambiguous means hidden" convention `VaultEntry.isOrphaned` uses. A genuinely filler
    /// row (never claimed) also reports orphaned here, since its `deletionToken` bytes are
    /// random and were never sealed, so they never decrypt. Callers that need to distinguish
    /// "orphaned" from "never claimed" use `isUnclaimed(usingKey:)` instead — see
    /// `VaultManager.Backup.liveRows(modelContext:)`/`claimFillerRow(modelContext:)`.
    func isOrphaned(usingKey key: SymmetricKey) -> Bool {
        guard let data = self.deletionToken, let plain = data.decrypt(using: key)
        else { return true }
        return plain != Self.liveToken
    }

    /// Whether this row has never been claimed by any depth — still filler. Checked via
    /// `depth` rather than `deletionToken`, so this stays independent of `isOrphaned`'s own
    /// fail-safe direction: a row that fails *both* `isOrphaned == false` and
    /// `isUnclaimed == false` is genuinely filler, not an orphaned-and-undecryptable row
    /// being misread as available. `depth` and `deletionToken` are always sealed together at
    /// claim time, so checking one is sufficient — they never disagree for a stored row.
    func isUnclaimed(usingKey key: SymmetricKey) -> Bool {
        guard let data = self.depth else { return true }
        return data.decrypt(using: key) == nil
    }

    // MARK: Init

    init(id: UUID = UUID(), depth: Data? = nil, deletionToken: Data? = nil, encryptedPayload: Data) {
        self.id               = id
        self.depth            = depth
        self.deletionToken    = deletionToken
        self.encryptedPayload = encryptedPayload
    }

    // MARK: AAD

    /// Authenticated additional data for AES-GCM seal/open of `encryptedPayload`.
    ///
    ///   id.uuidString (UTF-8)   — 36 bytes
    ///
    /// ⚠️ Sealed contract. Any change makes existing ciphertext unreadable.
    func aad() -> Data {
        self.id.uuidString.data(using: .utf8)!
    }

    // MARK: Sealed payload

    /// Plaintext sealed inside `encryptedPayload`.
    struct Payload: Codable {
        /// Raw 32-byte BEK. Sealed under vault key; never persisted in plaintext.
        let bekBytes: Data
        /// Stable UUID used as `entryID` in every BEK `SignedAttribute(.shard)`.
        /// Changes only on explicit BEK rotation, invalidating the prior distribution.
        let distributionID: UUID
        /// SSS shard distribution state for BEK shards. nil until first distribution.
        var shardMetadata: ShardDistributionMetadata?
    }
}
